site_name: Symply Docs (Pilot)
site_description: Symply product docs, guides, and manuals
theme:
  name: material
 # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/freshdesk.js
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
nav:
  - Home: index.md
  - Products:
      - SymplyPRO XTL:
          - Overview: products/symplypro-xtl/index.md
          - "XTL-40": products/symplypro-xtl/xtl-40/index.md

  - Knowledge Base:
      - Support:
          - "How to access Symply Support": kb/support/how-to-access-support.md
          - "TeamViewer (macOS)": kb/support/teamviewer-macos.md

      - LTO:
          - Install:
              - macOS: kb/lto/install/macos.md
              - Windows: kb/lto/install/windows.md
          - SymplyATOM:
              - "Scan for Drives": kb/lto/symplyatom/scan-for-drives.md
              - "Mount / Unmount": kb/lto/symplyatom/mount-unmount.md
              - "Host Validation": kb/lto/symplyatom/host-validation.md
              - "Retrieve Log": kb/lto/symplyatom/retrieve-log.md
          - Management:
              - "Firmware downloads": kb/lto/management/firmware-downloads.md
              - "Setting Max Transfer Size": kb/lto/management/setting-max-transfer-size.md
          - Troubleshooting:
              - "Error code 8": kb/lto/troubleshooting/error-code-8.md
              - "Mac: device not found": kb/lto/troubleshooting/cannot-find-product-mac.md
          - FAQ:
              - "What is LTO-9": kb/lto/faq/what-is-lto9.md

      - Thunderbolt:
          - "System requirements": kb/thunderbolt/system-requirements.md
          - "Drivers & downloads": kb/thunderbolt/downloads.md
          - "ATTO SAS firmware update": kb/thunderbolt/atto-firmware-update.md

      - SymplyPRO SAS:
          - Overview: kb/pro-sas/index.md
          - Drivers: kb/pro-sas/drivers.md

      - SPARK:
          - "Firmware update": kb/spark/firmware-update.md
          - "Replace a failed HDD": kb/spark/replace-hdd.md

      - NEBULA:
          - "Connect to NEBULA": kb/nebula/connect.md
